import{S as p,i as f}from"./assets/vendor-46aac873.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerpolicy&&(n.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?n.credentials="include":e.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=t(e);fetch(e.href,n)}})();const g="https://pixabay.com/api/",y="41701983-23ca5d5908e2c78927e8095f2",L=new p(".gallery-item"),b=()=>{const r=new URL(g);return r.searchParams.append("key",y),r.searchParams.append("image_type","photo"),r.searchParams.append("orientation","horizontal"),r.searchParams.append("safesearch",!0),r},w=r=>{const o=b();return o.searchParams.append("q",r),fetch(o).then(t=>{if(!t.ok)throw new Error(`HTTP error! Status: ${t.status}`);return t.json()}).then(t=>t.hits).catch(t=>{throw console.error("Error fetching images:",t),t})},E=r=>{const o=document.getElementById("gallery");o.innerHTML="",r.forEach(t=>{const{webformatURL:s,largeImageURL:e,tags:n,likes:a,views:u,comments:m,downloads:h}=t;o.insertAdjacentHTML("beforeend",`
    <li class="gallery-item">
    <a href="${e}">
      <img src="${s}" alt="${n}"/>
    <a/>
    <p>Likes: ${a}<p/>
    <p>view: ${u}<p/>
    <p>comments: ${m}<p/>
    <p>downloads: ${h}<p/>
    </li>
    `)}),L.refresh()};let l=document.getElementById("loader"),d=document.getElementById("search-button");const I=()=>{l.style.display="block",d.disabled=!0},c=()=>{l.style.display="none",d.disabled=!1},i=(r,o="info")=>{f[o]({title:r,position:"topCenter"})},P=r=>{r.preventDefault();const t=document.getElementById("search-input").value.trim();if(t.length<3){i("Please enter a search query","warning");return}I(),w(t).then(s=>{c(),s.length>0?E(s):i("Sorry, there are no images matching your search query. Please try again.","error")}).catch(s=>{c(),i("Error fetching images. Pease try again later.","error")})},B=document.getElementById("form");B.addEventListener("submit",P);
//# sourceMappingURL=commonHelpers.js.map
